name: Build and Push Docker Image

on:
  push:
    branches:
       - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Determine changed services
      id: changed-services
      run: |
        SERVICES=""
        # Use 'git rev-parse --verify HEAD^' to check if the previous commit exists
        if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
        git diff --name-only HEAD^ HEAD | grep -q 'info-service/' && SERVICES+="info-service "
        git diff --name-only HEAD^ HEAD | grep -q 'catalogue-service/' && SERVICES+="catalogue-service "
        git diff --name-only HEAD^ HEAD | grep -q 'naming-service/' && SERVICES+="naming-service "
        else
        # Handle the case for the first commit or no previous commit
        git ls-files | grep -q 'info-service/' && SERVICES+="info-service "
        git ls-files | grep -q 'catalogue-service/' && SERVICES+="catalogue-service "
        git ls-files | grep -q 'naming-service/' && SERVICES+="naming-service "
        fi
        echo "Changed services: $SERVICES"

        # Write the output to an environment file (as `set-output` is deprecated)
        echo "services=$SERVICES" >> $GITHUB_ENV


    - name: Build and push Docker images for changed services
      run: |
        for service in ${{ steps.changed-services.outputs.services }}; do
          echo "Building and pushing $service"
          cd $service
          chmod +x ./gradlew
          ./gradlew clean build jib --image=docker.io/${{ secrets.DOCKER_USERNAME }}/$service:latest
          cd ..
        done
