name: Build and Push Docker Image

on:
  push:
    branches:
      # - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # - name: Determine changed services
    #   id: changed-files
    #   run: |
    #     SERVICES=()
    #     if git diff --name-only HEAD^ HEAD | grep 'catalogue-service/'; then
    #       SERVICES+=('catalogue-service')
    #     fi
    #     if git diff --name-only HEAD^ HEAD | grep 'naming-service/'; then
    #       SERVICES+=('naming-service')
    #     fi
    #     if git diff --name-only HEAD^ HEAD | grep 'info-service/'; then
    #       SERVICES+=('info-service')
    #     fi
    #     echo "Changed services: ${SERVICES[@]}"
    #     echo "::set-output name=services::${SERVICES[@]}"

    - name: Build and push Docker image
      run: |
          echo "Building and pushing info-service"
          cd info-service
          chmod +x ./gradlew
          ./gradlew clean build jib --image=docker.io/${{ secrets.DOCKER_USERNAME }}/info-service:latest
